### ISSUE TITLE
Move Zeiter Repo to Central Account

### ISSUE THREAD

**Issue by maxdobeck** [zeiter-io/zeiter#43]
Make a new account or project that is shared between collaborators.

**Comment by kapoorlakshya** [comment]
Doc -  https://help.github.com/articles/creating-a-new-organization-from-scratch/

Quick link:
![image](https://user-images.githubusercontent.com/4314581/31588976-8eb97300-b1ae-11e7-8114-14d145cec450.png)

**Comment by maxdobeck** [comment]
Cool!  I'll make that change when I get home

**Comment by maxdobeck** [comment]
Need to do the following:

- [ ] Decide on Organization name. Zeiter is taken.
- [ ] Choose or create an email billing address

**Comment by kapoorlakshya** [comment]
Come on! It only has 1 repo with 0 commits... 😐

https://github.com/zeiter

How about WorkTree? Email could be zeiter@gmail.com if you want.

**Comment by maxdobeck** [comment]
Free Gmail account works. I'll see if we can set up distributed access or
just share the password. In the meantime we can just have that email
forward to our private emails.

WorkTree is what I was thinking lol. Can't think of anything else to
represent org.

**Comment by maxdobeck** [comment]
We can only have hyphens and alphanumerics, all other characters are illegal.  Is `zeiter-io` ok?

**Comment by kapoorlakshya** [comment]
Yup.

**Comment by maxdobeck** [comment]
I'll transfer the repository after the last pull request.  Have to research the transfer too.  I think I just click the + while in the organization page and choose Import Repo, but unsure.

**Comment by kapoorlakshya** [comment]
Sounds good. I think the better way would be to transfer ownership in the repo settings. I think the issues will get transferred too. Cloning a repo may not transfer the issues.

**Comment by maxdobeck** [comment]
Transferred with issues.  Just didn't see the transfer button under settings.
