### ISSUE TITLE
Max - Fork zeiter and delete private branches from zeiter-io repo.

### ISSUE THREAD

**Issue by kapoorlakshya** [zeiter-io/zeiter#47]
I almost ended up deleting all the branches from zeiter-io repo without checking if you had a fork or not 😐. Please fork when you get a chance, and then we can only keep master and release branches on the central repo.

**Comment by maxdobeck** [comment]
I typically delete my local branches too. Full delete in the repo and
locally is ok.

**Comment by maxdobeck** [comment]
I just changed my remote origin URL.  Should be safe to delete at this point.

https://help.github.com/articles/changing-a-remote-s-url/
